# 판다스 데이터 분석

In [1]:
import numpy as np 
import pandas as pd

### 시리즈(Series)

In [2]:
s = pd.Series([9904312, 3448737, 2890451, 2466052],
              index=["서울", "부산", "인천", "대구"])
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [3]:
x = np.array([9904312, 3448737, 2890451, 2466052])
x

array([9904312, 3448737, 2890451, 2466052])

In [4]:
pd.Series(range(10,14))

0    10
1    11
2    12
3    13
dtype: int64

In [5]:
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [6]:
s.values

array([9904312, 3448737, 2890451, 2466052], dtype=int64)

In [7]:
s.name = "인구"
s.index.name = "도시"
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

#### 시리즈 연산

In [8]:
s / 1000000

도시
서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
Name: 인구, dtype: float64

#### 시리즈 인덱싱

In [9]:
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [10]:
s[1], s['부산']

(3448737, 3448737)

In [11]:
s[[0, 3, 1]]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [12]:
s[["서울", "대구", "부산"]]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [13]:
s[(250e4 < s) & (s < 500e4)]  # 인구가 250만 초과, 500만 미만인 경우

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [14]:
s[1:3]

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [15]:
s["부산":"대구"]  # 부산에서 대구까지 (대구도 포함)

도시
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [16]:
s0 = pd.Series(range(3), index=["a", "b", "c"])
s0

a    0
b    1
c    2
dtype: int64

In [17]:
s0.a

0

#### 시리즈와 딕셔너리 자료형

In [18]:
"서울" in s  # 인덱스 라벨 중에 서울이 있는가

True

In [19]:
"대전" in s  # 인덱스 라벨 중에 대전이 있는가

False

In [20]:
for k, v in s.items():
    print(f"{k} = {v}")

서울 = 9904312
부산 = 3448737
인천 = 2890451
대구 = 2466052


In [21]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158})
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [22]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158},
               index=["부산", "서울", "인천", "대전"])
s2

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64

In [23]:
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [25]:
ds = s - s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [26]:
s.values - s2.values

array([ 6511121, -6182745,   258416,   975894], dtype=int64)

In [27]:
ds.notnull()

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [28]:
ds[ds.notnull()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [29]:
# 인구 증가율(%)
rs = (s - s2) / s * 100
rs = rs[rs.notnull()]
rs

부산    1.610619
서울    2.754659
인천    8.940335
dtype: float64

#### 데이터의 갱신, 추가, 삭제

In [30]:
rs["부산"] = 1.63
rs

부산    1.630000
서울    2.754659
인천    8.940335
dtype: float64

In [31]:
rs["대구"] = 1.41
rs

부산    1.630000
서울    2.754659
인천    8.940335
대구    1.410000
dtype: float64

In [32]:
del rs["서울"]
rs

부산    1.630000
인천    8.940335
대구    1.410000
dtype: float64

In [35]:
s3 = pd.Series([9904312, 3448737, 2890451, 2466052],
              index=[["Capital", "Capital", "SouthEast", "SouthEast"],
                     ["서울", "인천", "부산", "대구"]])
s3

Capital    서울    9904312
           인천    3448737
SouthEast  부산    2890451
           대구    2466052
dtype: int64

### 데이터프레임(DataFrame)

In [45]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [41]:
df.values

array([['수도권', 9904312, 9631482, 9762546, 9853972, 0.0283],
       ['경상권', 3448737, 3393191, 3512547, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       ['경상권', 2466052, 2431774, 2456016, 2473990, 0.0141]], dtype=object)

In [42]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [46]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [47]:
df.index.name = "도시"
df.columns.name = "특성"
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [48]:
df.T

도시                  서울       부산       인천       대구
특성                                               
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

In [49]:
# "2010-2015 증가율"이라는 이름의 열 갱신
df["2010-2015 증가율"] = df["2010-2015 증가율"] * 100
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [50]:
# "2005-2010 증가율"이라는 이름의 열 추가
df["2005-2010 증가율"] = ((df["2010"] - df["2005"]) / df["2005"] * 100).round(2)
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2005-2010 증가율
도시                                                                       
서울  수도권  9904312  9631482  9762546  9853972           2.83          -1.34
부산  경상권  3448737  3393191  3512547  3655437           1.63          -3.40
인천  수도권  2890451  2632035  2517680  2466338           9.82           4.54
대구  경상권  2466052  2431774  2456016  2473990           1.41          -0.99

In [51]:
# "2010-2015 증가율"이라는 이름의 열 삭제
del df["2010-2015 증가율"]
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

#### 열 인덱싱

In [52]:
# 하나의 열만 인덱싱하면 시리즈가 반환된다.
df["지역"]

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [55]:
type(df["지역"])

pandas.core.series.Series

In [53]:
# 여러개의 열을 인덱싱하면 부분적인 데이터프레임이 반환된다.
df[["2010", "2015"]]

특성     2010     2015
도시                  
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [54]:
# 2010이라는 열을 반환하면서 데이터프레임 자료형을 유지
df[["2010"]]

특성     2010
도시         
서울  9631482
부산  3393191
인천  2632035
대구  2431774

In [56]:
type(df[["2010"]])

pandas.core.frame.DataFrame

In [57]:
df[0]

KeyError: 0

In [59]:
df['지역']

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [60]:
df2 = pd.DataFrame(np.arange(12).reshape(3, 4))
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [62]:
df2[0]

0    0
1    4
2    8
Name: 0, dtype: int32

#### 행 인덱싱 - Slicing

In [63]:
df[:1]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34

In [64]:
df[:'서울']

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34

In [65]:
df[1:2]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           -3.4

In [66]:
df['서울':'부산']

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

#### 개별 데이터 인덱싱 - [열], [행] 순서

In [68]:
df['2015']['서울']

9904312

In [84]:
# 연습 문제 4.1.3
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [85]:
# (1) 모든 학생의 수학 점수를 시리즈로
df['수학']

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [86]:
# (2) 모든 학생의 국어와 영어 점수를 데이터 프레임으로
df[['국어','영어']]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

In [87]:
# 모든 학생의 각 과목 평균 점수를 새로운 열로 추가
df['평균'] = df.mean(axis=1).round(2)
df

국어  영어  수학     평균
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  40  70  46.67

In [88]:
df['평균'] = ((df['국어'] + df['영어'] + df['수학']) / 3).round(2)
df

국어  영어  수학     평균
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  40  70  46.67

In [89]:
# (4) 방자의 영어 점수를 80점으로 수정하고 평균 점수도 다시 계산
del df['평균']
df['영어']['방자'] = 80
df['평균'] = df.mean(axis=1).round(2)
df

국어  영어  수학     평균
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  80  70  60.00

In [90]:
# (5) 춘향의 점수를 데이터프레임으로
df[:'춘향'].T

춘향
국어  80.00
영어  90.00
수학  90.00
평균  86.67

In [91]:
# (6) 향단의 점수를 시리즈로
df.T['향단']

국어    70.0
영어    60.0
수학    80.0
평균    70.0
Name: 향단, dtype: float64