# Numpy

### Numpy Array

In [1]:
# 리스트와 넘파이 어레이 속도 비교
import numpy as np 
np_arr = np.arange(100000)
nu_list = [i for i in range(100000)]

In [2]:
%%time
for i in range(100):
    sum(nu_list)

Wall time: 166 ms


In [3]:
%%time
for i in range(100):
    np.sum(np_arr)

Wall time: 5 ms


#### 1차원 배열 만들기

In [5]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(ar)

numpy.ndarray

In [7]:
ar.shape

(10,)

#### 벡터화 연산

In [12]:
al = [2 * i for i in range(10)]
al

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [13]:
2 * ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
2 * al

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [15]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [16]:
2 * a + b

array([12, 24, 36])

In [18]:
a == 2

array([False,  True, False])

In [19]:
b > 15

array([False,  True,  True])

In [20]:
(a == 2) & (b > 10)

array([False,  True, False])

#### 2차원 배열

In [22]:
c = np.array([[0, 1, 2], [3, 4, 5]])  # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
c.shape

(2, 3)

In [24]:
len(c), len(c[0])

(2, 3)

In [25]:
np.arange(10, 90, 10).reshape(2,-1)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [26]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [29]:
d.shape, d.ndim

((2, 3, 4), 3)

#### 배열의 인덱싱

In [30]:
a = np.array([0, 1, 2, 3, 4])
a[2]

2

In [31]:
a[-1]

4

In [33]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a[1, 0]

3

#### 배열 슬라이싱

In [34]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [35]:
a[:, 1:3]

array([[1, 2],
       [5, 6]])

#### 배열 인덱싱

In [39]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [41]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [42]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [43]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [44]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [46]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])