### 배열의 생성과 변형

In [1]:
import numpy as np

#### 자료형

In [2]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [3]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [4]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [6]:
x = np.array([1, 2, 3], dtype='float32')
x.dtype

dtype('float32')

#### Inf와 Nan

In [8]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

array([  0.,  inf, -inf,  nan])

In [9]:
np.log(0)

-inf

In [10]:
np.exp(-np.inf)

0.0

#### 배열 생성

In [12]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [13]:
a.dtype

dtype('float64')

In [14]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
c = np.zeros((2, 5), dtype="int")
c

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [16]:
c.dtype

dtype('int32')

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
np.ones_like(b)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
g = np.empty((4, 3))
g

array([[9.94485376e-312, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.82587015e+184],
       [1.31371836e-047, 3.53728680e-057, 2.62460438e+179],
       [7.60233547e-042, 1.92104931e-052, 2.67968331e-032]])

In [20]:
np.arange(10)  # 0 .. n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(3, 21, 2)  # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [22]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [23]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [24]:
np.log(np.logspace(0.1, 1, 10))

array([0.23025851, 0.46051702, 0.69077553, 0.92103404, 1.15129255,
       1.38155106, 1.61180957, 1.84206807, 2.07232658, 2.30258509])

#### 전치 연산 (Transpose)

In [25]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
A.T @ A

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [28]:
A @ A.T

array([[14, 32],
       [32, 77]])

#### 배열의 크기 변형

In [29]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a.reshape(-1, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a.reshape(3, 2, -1)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [34]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [38]:
x.reshape(1, -1)

array([[0, 1, 2, 3, 4]])

In [39]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [40]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

#### 배열 연결

In [41]:
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [43]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [44]:
b1 = np.ones((2, 3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 2차원 그리드 포인트 생성

In [48]:
x = np.arange(3)
x

array([0, 1, 2])

In [49]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [50]:
X, Y = np.meshgrid(x, y)

In [51]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [52]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [53]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]