### 배열의 연산

In [1]:
import numpy as np

#### 벡터화 연산

In [2]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [3]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

Wall time: 7 ms


In [4]:
%%time
z = x + y

Wall time: 2 ms


In [5]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [7]:
np.all(a == b)

False

In [8]:
np.all(a == c)

True

In [9]:
a = np.arange(1,11)
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [10]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

#### 스칼라와 벡터/행렬의 곱셈

In [11]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [13]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

#### 브로드캐스팅

In [15]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [16]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [17]:
x + y

array([1, 2, 3, 4, 5])

In [18]:
x + 1

array([1, 2, 3, 4, 5])

#### 차원 축소

In [19]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [20]:
np.sum(x)

6

In [21]:
np.sum(x, axis=0)

array([3, 3])

In [22]:
np.sum(x, axis=1)

array([2, 4])

In [23]:
x = np.linspace(1.0, 10.0, 30).reshape(5, 6).round(2)
x

array([[ 1.  ,  1.31,  1.62,  1.93,  2.24,  2.55],
       [ 2.86,  3.17,  3.48,  3.79,  4.1 ,  4.41],
       [ 4.72,  5.03,  5.34,  5.66,  5.97,  6.28],
       [ 6.59,  6.9 ,  7.21,  7.52,  7.83,  8.14],
       [ 8.45,  8.76,  9.07,  9.38,  9.69, 10.  ]])

In [24]:
np.sum(x), x.sum()

(165.0, 165.0)

In [25]:
np.sum(x, axis=1), x.sum(axis=1)

(array([10.65, 21.81, 33.  , 44.19, 55.35]),
 array([10.65, 21.81, 33.  , 44.19, 55.35]))

#### 정렬

In [26]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [27]:
np.sort(a)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [28]:
np.sort(a, axis=1)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [29]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [30]:
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [31]:
a.sort()

In [32]:
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

#### 내림차순으로 정렬

In [33]:
a = np.random.rand(10).round(2)
a

array([0.1 , 0.06, 0.16, 0.1 , 0.64, 0.46, 0.85, 0.59, 0.08, 0.65])

In [34]:
a.sort()
a = a[::-1]
a

array([0.85, 0.65, 0.64, 0.59, 0.46, 0.16, 0.1 , 0.1 , 0.08, 0.06])

In [35]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [36]:
a.sort()
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [37]:
a = a[:, ::-1]
a

array([[ 7,  5,  4,  3],
       [12, 11,  9,  1],
       [15, 14,  2,  1]])

In [38]:
a.sort(axis=0)
a

array([[ 7,  5,  2,  1],
       [12, 11,  4,  1],
       [15, 14,  9,  3]])

In [39]:
a = a[::-1, :]
a

array([[15, 14,  9,  3],
       [12, 11,  4,  1],
       [ 7,  5,  2,  1]])