### 난수 발생과 카운팅

In [1]:
import numpy as np

### 시드 설정하기

In [2]:
np.random.rand(5)

array([0.53487943, 0.99448428, 0.06397474, 0.53390167, 0.47053843])

In [3]:
np.random.rand(5)

array([0.471479  , 0.87850107, 0.50800987, 0.52725271, 0.20272775])

In [4]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

In [5]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

#### 데이터의 순서 바꾸기

In [6]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.random.shuffle(x)
x

array([5, 7, 6, 4, 3, 1, 2, 8, 9, 0])

#### 데이터 샘플링

In [8]:
np.random.choice(5, 5, replace=False)  # shuffle 명령과 같다.

array([4, 0, 1, 2, 3])

In [11]:
np.random.choice(5, 5, replace=True)

array([4, 2, 3, 4, 1])

In [12]:
np.random.choice(5, 3, replace=False)  # 3개만 선택

array([0, 3, 2])

In [13]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  # 선택 확률을 다르게 해서 10개 선택

array([3, 2, 3, 2, 2, 3, 3, 3, 3, 2])

#### 난수 생성

In [14]:
np.random.rand(5)

array([0.84924802, 0.44237258, 0.83146771, 0.76392072, 0.91969098])

In [15]:
np.random.randn(10)

array([ 0.83209585,  2.04520542, -0.31681392, -1.31283291, -1.75445746,
        0.10209408, -1.36150208,  0.48178488, -0.20832874, -0.09186351])

In [16]:
np.random.randint(10, size=10)

array([3, 7, 7, 2, 5, 0, 0, 8, 3, 6])

In [17]:
np.random.randint(10, 20, size=10)

array([13, 14, 16, 19, 15, 12, 14, 13, 10, 19])

In [19]:
x = np.random.randn(250) * 100 + 10000
x[:10]

array([ 9993.74440931, 10025.51913858,  9900.07147867, 10027.00357746,
        9939.53695882, 10001.66325538, 10026.91362805, 10007.92513712,
        9988.90602303, 10051.63559416])

In [22]:
price = 10000
tomorrow = price * (1 + np.random.randn(1)/100.)
tomorrow[0]

9981.042356108463

In [23]:
# 연습문제 3.5.2
prices = []
price = 10000
for i in range(250):
    tmp = price * (1 + np.random.randn(1)/100.)
    price = tmp[0]
    prices.append(price)
prices[:10]

[10043.439186269752,
 10122.014319551208,
 9937.158073433466,
 10094.82038454138,
 10035.49761146914,
 9960.396398418503,
 10098.109343510754,
 10030.971283552912,
 9994.847402515654,
 9985.972415637254]

#### 정수 데이터 카운팅

In [25]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [26]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [27]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [28]:
count

array([2, 2, 1], dtype=int64)

In [29]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)