### 벡터와 벡터의 곱셈

In [1]:
import numpy as np 

In [3]:
x = np.arange(1, 4).reshape(3, 1)
x

array([[1],
       [2],
       [3]])

In [4]:
y = np.arange(4, 7).reshape(3, 1)
y

array([[4],
       [5],
       [6]])

In [5]:
x.shape, y.shape

((3, 1), (3, 1))

In [6]:
x.T.shape

(1, 3)

In [7]:
z = x.T @ y
z

array([[32]])

In [8]:
z.shape

(1, 1)

In [9]:
z[0,0]

32

In [10]:
np.dot(x.T, y)

array([[32]])

In [12]:
x = np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
x @ x.T

array([[14, 32],
       [32, 77]])

In [14]:
y = x.T

In [23]:
def mat_mul(x, y):
    z = np.zeros((len(x), len(y[0])))
    if len(x[0]) != len(y):
        return z
    for i in range(len(x)):
        for m in range(len(y[0])):
            val = 0
            for k in range(len(x[0])):
                val += x[i, k] * y[k, m]
            z[i, m] = val
    return z

In [24]:
x = np.arange(1,7).reshape(3,2)

In [25]:
y = x.T

In [26]:
z = mat_mul(x, y)
z

array([[ 5., 11., 17.],
       [11., 25., 39.],
       [17., 39., 61.]])

In [27]:
np.dot(x, y)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [31]:
# 연습문제 2.2.1
p = np.array([100, 80, 50]) * 10000
p = p.reshape(1, 3)

In [32]:
n = np.array([3, 4, 5]).reshape(3, 1)

In [33]:
money = (p @ n)[0, 0]
money

8700000